apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app

    spec:
      containers:
        - name: django-app-container
          image: django-image
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
              name: gunicorn
              protocol: TCP
